apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: req-transformer
  annotations:
    kubernetes.io/ingress.class: kong
config: 
  replace:
    uri: "/$(uri_captures['version'])/"
plugin: request-transformer
